vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<Up>", "<Nop>")
vim.keymap.set("n", "<Down>", "<Nop>")
vim.keymap.set("n", "<Left>", "<Nop>")
vim.keymap.set("n", "<Right>", "<Nop>")
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("i", "jK", "<Esc>")
vim.keymap.set("i", "Jk", "<Esc>")
vim.keymap.set("i", "JK", "<Esc>")
vim.keymap.set("v", "jk", "<Esc>")
vim.keymap.set("v", "jK", "<Esc>")
vim.keymap.set("v", "Jk", "<Esc>")
vim.keymap.set("v", "JK", "<Esc>")
vim.keymap.set("t", "jk", "<Esc>")
vim.keymap.set("t", "jK", "<Esc>")
vim.keymap.set("t", "Jk", "<Esc>")
vim.keymap.set("t", "JK", "<Esc>")
